export const CLICK_CART_BUTTON = 'CLICK_CART_BUTTON';
export const CLICK_BROWSE_BUTTON = 'CLICK_BROWSE_BUTTON';

export const CLICK_ADD_TO_CART_BUTTON = 'CLICK_ADD_TO_CART_BUTTON';
export const CLICK_PRODUCT = 'CLICK_PRODUCT';