export const CLICK_CART_BUTTON = 'CLICK_CART_BUTTON';
export const CLICK_BROWSE_BUTTON = 'CLICK_BROWSE_BUTTON';

export const CLICK_ADD_TO_CART_BUTTON = 'CLICK_ADD_TO_CART_BUTTON';
export const CLICK_PRODUCT = 'CLICK_PRODUCT';

export const TRIGGER_NUTRIWELL_CHECK_BOX = 'TRIGGER_NUTRIWELL_CHECK_BOX';
export const TRIGGER_MARIGOLD_CHECK_BOX = 'TRIGGER_MARIGOLD_CHECK_BOX';
export const TRIGGER_0_TO_2DOT05_CHECK_BOX = 'TRIGGER_0_TO_2DOT05_CHECK_BOX';
export const TRIGGER_2DOT05_TO_2DOT35_CHECK_BOX = 'TRIGGER_2DOT05_TO_2DOT35_CHECK_BOX';